[workspace]
resolver = "2"
members = [
    "attr"
]


[workspace.package]
edition = "2021"
version = "0.1.0"

[workspace.dependencies]
heck = { version = "^0.5", default-features = false }
quote = { version = "^1", default-features = false }
syn = { version = "^2", default-features = false }
