[package]
name = "generic-array-struct-attr"
version = "0.1.0"
edition = { workspace = true }

[lib]
proc-macro = true

[dependencies]
heck = { workspace = true }
quote = { workspace = true }
syn = { workspace = true, features = ["derive", "parsing", "printing", "proc-macro"] }
